# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f81fb8b0fbb0f48aa6b9a949462bd7aea93a41f21532b9f73fce06998def394520f5f4344b7d4266fec5b67711470d9f46f1591a1e47b5eb435b084eb6b1eb0c

test:
  secret_key_base: 204f6bfa29142c263d997fcd1d0146f25b9fa52b79c5eb5dd86b287b17858986ac4c59b51bd76e7492a759fa6dad435f959a4d041b4e4aa265a67ee38ee8aeb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
